version: "3.3"

services:
  ohjelmat:
    image: "vihreat-ohjelmat-app-dev"
    container_name: "vihreat-ohjelmat"
    build:
      dockerfile: "./vihreat-ohjelmat/dev.Dockerfile"
    ports:
      - "5176:5176"
    volumes:
      - "./vihreat-ohjelmat:/vihreat-ohjelmat"
    depends_on:
      - atomic
  atomic:
    image: "joepmeneer/atomic-server:master"
    container_name: "atomic"
    ports:
      - "9883:9883"
      - "9884:9884"
    volumes:
      - "atomic-storage:/atomic-storage"
    platform: "linux/amd64"
    env_file: "dev.env"
volumes:
  atomic-storage:
  vihreat-ohjelmat: