version: "3.3"

services:
  ohjelmat:
    image: "vihreat-ohjelmat-app"
    container_name: "vihreat-ohjelmat"
    build:
      dockerfile: "./vihreat-ohjelmat/Dockerfile"
    ports:
      - "80:80"

  atomic:
    image: "joepmeneer/atomic-server:master"
    container_name: "atomic"
    ports:
      - "9883:9883"
      - "9884:9884"
    volumes:
      - "atomic-storage:/atomic-storage"
    platform: "linux/amd64"
    environment:
      ATOMIC_PORT: 9883
      ATOMIC_PORT_HTTPS: 9884
      ATOMIC_DOMAIN: "localhost"
      ATOMIC_HTTPS: "false"
  
volumes:
  atomic-storage: